### PR TITLE
Handle `aud` claims like API contexts from WSO2

### PR DESCRIPTION
**Pull request by GaryGSC**

### CODE REVIEW

**Comment by GaryGSC** [comment]
Still need to update tests.

**Comment by GaryGSC** [comment]
Added tests for the existing API context functionality to prove we didn't break anything with this change.

Added some skipped tests for the new `aud` functionality. Is there a convenient way for me to programmatically get a JWT from TYK? I mainly ask because I'd want one that isn't expired for testing.

**Review by Gi60s — APPROVED** [review]

**Comment by Gi60s** [comment]
It would be good to find a way to get a JWT from Tyk for those two skipped tests, but this is good for now.

**Review by dwclogic — COMMENTED** [review]
Looks good! I look forward to seeing this working!

**Pull request merged**
